/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux labu36.unix.lab. 2.6.30.3-lab i686"
#define LGL_COMPILED "Thu Mar  3 21:56:03 ART 2011"
#define LGL_RELEASED "Sat Jul 31 11:52:29 CEST 2010"
#define LGL_VERSION "276"
#define LGL_ID "6264d55e84105d420ec6e7f27ad0fad15f5885a4"
