/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Darwin 205-142-18-190.fibertel.com.ar 10.2.0 i386"
#define LGL_COMPILED "Tue Jan 11 21:14:59 WARST 2011"
#define LGL_RELEASED "Sat Jul 31 11:52:29 CEST 2010"
#define LGL_VERSION "276"
#define LGL_ID "6264d55e84105d420ec6e7f27ad0fad15f5885a4"
