[experiment]
id: working_test
take: 1
java_test: roops.core.objects.BinomialHeapExtractTest
tasks: ./andrea/tasks
timeout: 20
jvm_heap_initial: 300M
jvm_heap_maximum: 300M
jvm_thread_stack: 16M

[logging]
weather_reports: Yes
weather_every: 10
events_stdout: task|wrep

[paths]
java_home: /usr/bin/java
local_storage: ./andrea/andrea-localstore
minisat_binary: ../../minisat/220/core/minisat_release
als2rels: ./als2rels.jar
als2cnf: ./als2cnf.jar

[alloy]
class_name: rfm.alloy.CLI
class_path: ./alloycli-160b2.jar
shlib_path: ./x86-mac
[general]
allow_clobbering: Yes
