/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kodkod_engine_satlab_MiniSat220Simp */

#ifndef _Included_kodkod_engine_satlab_MiniSat220Simp
#define _Included_kodkod_engine_satlab_MiniSat220Simp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    make
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_make
  (JNIEnv *, jclass);

/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    addVariables
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_addVariables
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    addClause
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_addClause
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    solve
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_MiniSat220Simp
 * Method:    valueOf
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_MiniSat220Simp_valueOf
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
